---
- name: pulling scientific_calculator docker image
  hosts: all
  tasks:             
          - name: Pulling junit devops image 
            docker_image:
                  name: ganeshmalladi/spe_miniproject
                  source: pull

          - name: creating an updated container
            shell: docker run -id ganeshmalladi/spe_miniproject
