---
- name: pulling scientific_calculator docker image
  hosts: all
  tasks:             
          - name: Pulling junit devops image 
            docker_image:
                  name: ganeshmalladi/scientific_calculator
                  source: pull

          - name: creating an updated container
            shell: docker run -id ganeshmalladi/scientific_calculator